[build]
  command = "npm run build && npm run export"
  publish = "out"

[dev]
  command = "npm run dev"

[[plugins]]
# netlify nextjs plugin that helps nextjs ISR and SSR and API routes, etc
package = "@netlify/plugin-nextjs"